// <auto-generated />
namespace Humber_Timesheet_Tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTeacherPic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTeacherPic));
        
        string IMigrationMetadata.Id
        {
            get { return "202206142120014_AddTeacherPic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
